# Generated by Django 5.1.5 on 2025-02-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='data_criação',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='pontuacao',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('MC', 'Múltipla Escolha'), ('VF', 'Verdadeiro ou Falso')], default='MC', max_length=2),
        ),
        migrations.AddField(
            model_name='sala',
            name='iniciada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tempo_resposta',
            field=models.IntegerField(default=20),
        ),
    ]
