# Generated by Django 5.1.5 on 2025-06-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='pontuacao',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='resposta',
            name='tempo_resposta',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='sala',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='quizzes.quiz'),
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correta', models.BooleanField()),
                ('tempo_resposta', models.FloatField()),
                ('pontuacao', models.IntegerField()),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.jogador')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.pergunta')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.resposta')),
            ],
        ),
    ]
